alias tf=terraform

alias tfS='tf show'
alias tfr='tf refresh'
alias tfi='tf init'
alias tfim='tf init -migrate-state'
alias tfiu='tf init -upgrade'
alias tfo='tf output'
alias tfv='tf validate'
alias tfV='tf version'
alias tff='tf fmt'
alias tfg='tf get'
alias tfaa='tf apply -auto-approve -input=false'
alias tfa='tf apply -input=false'
alias tfp='tf plan -input=false'
alias tfda='tf destroy -auto-approve -input=false'
alias tfd='tf destroy -input=false'
alias tft='tf taint'
alias tfu='tf untaint'
alias tfs='tf state'
alias tfsl='tf state list'
alias tfsp='tf state pull | less'
alias tfsr='tf state rm'
alias tfsm='tf state mv'
alias tfss='tf state show'
alias tfm='tf import'


alias tg=terragrunt
alias tga='tg apply'
alias tgaa='tg apply -auto-approve'
alias tgra='tg run-all apply'
alias tgrp='tg run-all plan'
alias tgrd='tg run-all destroy'
alias tgrda='tg run-all destroy -auto-approve'
alias tgf='tg hclfmt'
alias tgv='tg validate-inputs --terragrunt-strict-validate'