---
- name: run node exporter
  community.docker.docker_container:
    name: node-exporter
    image: quay.io/prometheus/node-exporter:v1.3.1
    state: started
    restart_policy: always
    network_mode: host
    pid_mode: host
    log_driver: json-file
    log_options:
      max-size: 30m
      max-file: "3"
    volumes:
      - "/:/host:ro,rslave"
    command:
      - "--path.rootfs=/host"