---
- name: get ethernet interface
  pause:
    prompt: network interface (eg eth0)?
  register: network_interface

- name: get ip address
  pause:
    prompt: ip address cidr (eg 1.1.1.1/24)?
  register: ip_address

- name: get dns 1
  pause:
    prompt: dns 1?
  register: dns_1

- name: get dns 2
  pause:
    prompt: dns 2?
  register: dns_2

- name: get gateway address
  pause:
    prompt: gateway address?
  register: gateway_address

- name: check if /etc/netplan exists
  ansible.builtin.stat:
    path: /etc/netplan
  register: netplan

- name: get existing netplan file
  ansible.builtin.find:
    paths: /etc/netplan
    file_type: file
  register: netplan_files
  when:
    - netplan.stat.exists

- name: fail if there are more than 1 netplan
  ansible.builtin.fail:
    msg: There are more than one netplan configuration.
  when:
    - netplan.stat.exists
    - netplan_files.matched > 1

- name: set netplan static ip
  become: true
  ansible.builtin.template:
    src: netplan.yaml
    dest: "{{ netplan_files.files[0].path }}"
  when: netplan.stat.exists

- name: check if /etc/dhcpcd.conf exists
  ansible.builtin.stat:
    path: /etc/dhcpcd.conf
  register: dhcpcd

- name: set dhcpcd static ip
  become: true
  ansible.builtin.blockinfile:
    path: /etc/dhcpcd.conf
    state: present
    block: |
      interface {{ network_interface.user_input }}
      static ip_address={{ ip_address.user_input }}
      static routers={{ gateway_address.user_input }}
      static domain_name_servers={{ dns_1.user_input }} {{ dns_2.user_input }}
  when: dhcpcd.stat.exists